module.exports = [
  {
    title: "Digital Marketing Specialist",
    category: "Business",
    description: "Plans and runs online campaigns for Nepal-based brands and SMEs.",
    salary_range: {
      entry_min: 20000,
      entry_max: 35000,
      mid_min: 40000,
      mid_max: 70000,
      senior_min: 80000,
      senior_max: 150000,
      currency: "NPR",
    },
    demand_indicator: "High",
    qualification_required: ["+2", "Marketing Diploma", "Bachelor's"],
    time_to_employment_months: 3,
    risk_index: "Low",
    locations: ["Kathmandu", "Pokhara", "Butwal"],
    required_skills: ["Content", "Ads", "Analytics", "SEO"],
    education_cost_range: {
      min: 80000,
      max: 250000,
      currency: "NPR",
    },
    education_duration_years: 1,
  },
  {
    title: "Software Engineer",
    category: "Technology",
    description: "Builds and maintains web or mobile applications.",
    salary_range: {
      entry_min: 30000,
      entry_max: 50000,
      mid_min: 60000,
      mid_max: 100000,
      senior_min: 120000,
      senior_max: 220000,
      currency: "NPR",
    },
    demand_indicator: "High",
    qualification_required: ["Bachelor's", "BIT", "BSc CS"],
    time_to_employment_months: 4,
    risk_index: "Medium",
    locations: ["Kathmandu", "Pokhara", "Biratnagar"],
    required_skills: ["JavaScript", "APIs", "Databases"],
    education_cost_range: {
      min: 400000,
      max: 1200000,
      currency: "NPR",
    },
    education_duration_years: 4,
  },
  {
    title: "Data Analyst",
    category: "Technology",
    description: "Analyzes data to support business decisions.",
    salary_range: {
      entry_min: 25000,
      entry_max: 45000,
      mid_min: 50000,
      mid_max: 90000,
      senior_min: 100000,
      senior_max: 170000,
      currency: "NPR",
    },
    demand_indicator: "Medium",
    qualification_required: ["Bachelor's", "Statistics", "IT"],
    time_to_employment_months: 5,
    risk_index: "Medium",
    locations: ["Kathmandu", "Pokhara"],
    required_skills: ["Excel", "SQL", "Visualization"],
    education_cost_range: {
      min: 400000,
      max: 900000,
      currency: "NPR",
    },
    education_duration_years: 4,
  },
  {
    title: "Civil Engineer",
    category: "Engineering",
    description: "Designs and supervises infrastructure projects.",
    salary_range: {
      entry_min: 25000,
      entry_max: 45000,
      mid_min: 50000,
      mid_max: 90000,
      senior_min: 100000,
      senior_max: 180000,
      currency: "NPR",
    },
    demand_indicator: "Medium",
    qualification_required: ["Bachelor's", "BE Civil"],
    time_to_employment_months: 6,
    risk_index: "Medium",
    locations: ["Kathmandu", "Pokhara", "Dharan"],
    required_skills: ["AutoCAD", "Project Planning", "Surveying"],
    education_cost_range: {
      min: 600000,
      max: 1200000,
      currency: "NPR",
    },
    education_duration_years: 4,
  },
  {
    title: "Nurse",
    category: "Healthcare",
    description: "Provides patient care in hospitals and clinics.",
    salary_range: {
      entry_min: 20000,
      entry_max: 35000,
      mid_min: 40000,
      mid_max: 70000,
      senior_min: 80000,
      senior_max: 120000,
      currency: "NPR",
    },
    demand_indicator: "High",
    qualification_required: ["PCL Nursing", "BSc Nursing"],
    time_to_employment_months: 4,
    risk_index: "Low",
    locations: ["Kathmandu", "Pokhara", "Dharan"],
    required_skills: ["Patient Care", "Clinical Skills", "Communication"],
    education_cost_range: {
      min: 500000,
      max: 900000,
      currency: "NPR",
    },
    education_duration_years: 3,
  },
  {
    title: "Accountant",
    category: "Business",
    description: "Manages accounts, taxes, and financial reporting.",
    salary_range: {
      entry_min: 20000,
      entry_max: 35000,
      mid_min: 40000,
      mid_max: 70000,
      senior_min: 80000,
      senior_max: 140000,
      currency: "NPR",
    },
    demand_indicator: "Medium",
    qualification_required: ["BBA", "BBS", "CA Foundation"],
    time_to_employment_months: 4,
    risk_index: "Medium",
    locations: ["Kathmandu", "Pokhara", "Biratnagar"],
    required_skills: ["Accounting", "Tax", "Excel"],
    education_cost_range: {
      min: 300000,
      max: 800000,
      currency: "NPR",
    },
    education_duration_years: 4,
  },
  {
    title: "Graphic Designer",
    category: "Creative",
    description: "Creates visual content for brands and media.",
    salary_range: {
      entry_min: 18000,
      entry_max: 30000,
      mid_min: 35000,
      mid_max: 60000,
      senior_min: 70000,
      senior_max: 120000,
      currency: "NPR",
    },
    demand_indicator: "Medium",
    qualification_required: ["+2", "Design Diploma", "Bachelor's"],
    time_to_employment_months: 3,
    risk_index: "Medium",
    locations: ["Kathmandu", "Pokhara"],
    required_skills: ["Design", "Branding", "UI"],
    education_cost_range: {
      min: 80000,
      max: 300000,
      currency: "NPR",
    },
    education_duration_years: 1,
  },
  {
    title: "Tourism and Hospitality Manager",
    category: "Hospitality",
    description: "Manages hotels, travel, and tourism operations.",
    salary_range: {
      entry_min: 20000,
      entry_max: 35000,
      mid_min: 40000,
      mid_max: 70000,
      senior_min: 80000,
      senior_max: 150000,
      currency: "NPR",
    },
    demand_indicator: "Medium",
    qualification_required: ["Bachelor's", "Hotel Management"],
    time_to_employment_months: 5,
    risk_index: "Medium",
    locations: ["Kathmandu", "Pokhara", "Chitwan"],
    required_skills: ["Operations", "Customer Service", "Leadership"],
    education_cost_range: {
      min: 300000,
      max: 700000,
      currency: "NPR",
    },
    education_duration_years: 4,
  },
  {
    title: "Agriculture Technician",
    category: "Agriculture",
    description: "Supports modern farming and agribusiness practices.",
    salary_range: {
      entry_min: 18000,
      entry_max: 30000,
      mid_min: 35000,
      mid_max: 60000,
      senior_min: 70000,
      senior_max: 110000,
      currency: "NPR",
    },
    demand_indicator: "Medium",
    qualification_required: ["Diploma", "BSc Agriculture"],
    time_to_employment_months: 5,
    risk_index: "Medium",
    locations: ["Chitwan", "Butwal", "Biratnagar"],
    required_skills: ["Soil", "Crop Planning", "Field Work"],
    education_cost_range: {
      min: 250000,
      max: 600000,
      currency: "NPR",
    },
    education_duration_years: 4,
  },
  {
    title: "Banking Officer",
    category: "Finance",
    description: "Handles retail and corporate banking operations.",
    salary_range: {
      entry_min: 22000,
      entry_max: 38000,
      mid_min: 45000,
      mid_max: 80000,
      senior_min: 90000,
      senior_max: 160000,
      currency: "NPR",
    },
    demand_indicator: "Medium",
    qualification_required: ["BBA", "BBS", "MBA"],
    time_to_employment_months: 4,
    risk_index: "Medium",
    locations: ["Kathmandu", "Pokhara", "Biratnagar"],
    required_skills: ["Finance", "Communication", "Customer Service"],
    education_cost_range: {
      min: 350000,
      max: 800000,
      currency: "NPR",
    },
    education_duration_years: 4,
  },
  {
    title: "Secondary School Teacher",
    category: "Education",
    description: "Teaches subjects at the secondary level.",
    salary_range: {
      entry_min: 20000,
      entry_max: 32000,
      mid_min: 35000,
      mid_max: 55000,
      senior_min: 60000,
      senior_max: 90000,
      currency: "NPR",
    },
    demand_indicator: "Low",
    qualification_required: ["Bachelor's", "BEd"],
    time_to_employment_months: 6,
    risk_index: "High",
    locations: ["Kathmandu", "Pokhara", "Dharan"],
    required_skills: ["Teaching", "Communication", "Planning"],
    education_cost_range: {
      min: 300000,
      max: 700000,
      currency: "NPR",
    },
    education_duration_years: 4,
  },
  {
    title: "IT Support Technician",
    category: "Technology",
    description: "Provides technical support for systems and networks.",
    salary_range: {
      entry_min: 20000,
      entry_max: 35000,
      mid_min: 40000,
      mid_max: 70000,
      senior_min: 80000,
      senior_max: 130000,
      currency: "NPR",
    },
    demand_indicator: "Medium",
    qualification_required: ["Diploma", "BIT", "BSc CS"],
    time_to_employment_months: 3,
    risk_index: "Low",
    locations: ["Kathmandu", "Pokhara", "Biratnagar"],
    required_skills: ["Networking", "Troubleshooting", "Windows"],
    education_cost_range: {
      min: 100000,
      max: 300000,
      currency: "NPR",
    },
    education_duration_years: 1,
  },
];
