module.exports = [
  {
    title: "JavaScript Fundamentals",
    description: "Learn core JavaScript concepts for web development.",
    provider: "freeCodeCamp",
    url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
    duration_hours: 20,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["JavaScript"],
    tags: ["web", "programming"],
  },
  {
    title: "REST API Basics",
    description: "Build and consume REST APIs with Node and Express.",
    provider: "YouTube",
    url: "https://www.youtube.com/watch?v=Oe421EPjeBE",
    duration_hours: 6,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["APIs"],
    tags: ["backend", "api"],
  },
  {
    title: "SQL for Data Analysis",
    description: "Query data using SQL and understand joins.",
    provider: "Khan Academy",
    url: "https://www.khanacademy.org/computing/computer-programming/sql",
    duration_hours: 10,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["SQL", "Databases"],
    tags: ["data", "database"],
  },
  {
    title: "Excel Essentials",
    description: "Learn Excel for reporting and analysis.",
    provider: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/training/paths/get-started-excel/",
    duration_hours: 8,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Excel", "Analytics"],
    tags: ["data", "analysis"],
  },
  {
    title: "Data Visualization Basics",
    description: "Create charts and dashboards with best practices.",
    provider: "Coursera",
    url: "https://www.coursera.org/learn/data-visualization",
    duration_hours: 12,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Visualization"],
    tags: ["data", "visualization"],
  },
  {
    title: "SEO Essentials",
    description: "Improve search rankings with on-page SEO.",
    provider: "Google Digital Garage",
    url: "https://learndigital.withgoogle.com/digitalgarage/course/seo-fundamentals",
    duration_hours: 5,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["SEO"],
    tags: ["marketing"],
  },
  {
    title: "Digital Ads Starter",
    description: "Learn the basics of paid ads and targeting.",
    provider: "Meta Blueprint",
    url: "https://www.facebook.com/business/learn",
    duration_hours: 6,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Ads"],
    tags: ["marketing"],
  },
  {
    title: "Customer Service Foundations",
    description: "Deliver great customer service and handle requests.",
    provider: "Coursera",
    url: "https://www.coursera.org/learn/customer-service-fundamentals",
    duration_hours: 8,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Customer Service", "Communication"],
    tags: ["service"],
  },
  {
    title: "Leadership Essentials",
    description: "Lead teams and build influence at work.",
    provider: "edX",
    url: "https://www.edx.org/learn/leadership",
    duration_hours: 10,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Leadership"],
    tags: ["management"],
  },
  {
    title: "AutoCAD Basics",
    description: "Learn AutoCAD tools and drafting workflows.",
    provider: "Autodesk",
    url: "https://www.autodesk.com/learn/ondemand/curated/autocad",
    duration_hours: 12,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["AutoCAD"],
    tags: ["engineering"],
  },
  {
    title: "Clinical Skills for Nursing",
    description: "Core clinical skills for nursing practice.",
    provider: "OpenLearn",
    url: "https://www.open.edu/openlearn/health-sports-psychology/health/clinical-skills/content-section-0",
    duration_hours: 6,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Clinical Skills", "Patient Care"],
    tags: ["healthcare"],
  },
  {
    title: "Project Planning Basics",
    description: "Plan project timelines and deliverables.",
    provider: "Coursera",
    url: "https://www.coursera.org/learn/project-planning",
    duration_hours: 8,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Project Planning"],
    tags: ["management"],
  },
  {
    title: "Networking Fundamentals",
    description: "Learn network components and configurations.",
    provider: "Cisco Networking Academy",
    url: "https://www.netacad.com/courses/networking",
    duration_hours: 15,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Networking"],
    tags: ["it"],
  },
  {
    title: "Windows Troubleshooting",
    description: "Fix common Windows OS issues and errors.",
    provider: "Microsoft Learn",
    url: "https://learn.microsoft.com/en-us/troubleshoot/windows-client/",
    duration_hours: 6,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Troubleshooting", "Windows"],
    tags: ["it"],
  },
  {
    title: "Agriculture Soil Basics",
    description: "Understand soil health and crop planning.",
    provider: "FAO",
    url: "https://www.fao.org/soil-portal/en/",
    duration_hours: 5,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Soil", "Crop Planning", "Field Work"],
    tags: ["agriculture"],
  },
  {
    title: "Nepal Digital Marketing Basics",
    description: "Local market digital marketing fundamentals.",
    provider: "Nepal Digital Academy",
    url: "https://example.com/nepal-digital-marketing",
    duration_hours: 7,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Content", "SEO", "Ads", "Analytics"],
    tags: ["marketing", "nepal"],
  },
  {
    title: "Nepal UI Design Starter",
    description: "Intro to UI design with local product examples.",
    provider: "Kathmandu Design School",
    url: "https://example.com/nepal-ui-design",
    duration_hours: 9,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["UI", "Design", "Branding"],
    tags: ["design", "nepal"],
  },
  {
    title: "Nepal Accounting Essentials",
    description: "Accounting fundamentals with Nepal tax context.",
    provider: "Nepal Finance Institute",
    url: "https://example.com/nepal-accounting",
    duration_hours: 10,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Accounting", "Tax", "Excel"],
    tags: ["finance", "nepal"],
  },
  {
    title: "Hospitality Service Excellence",
    description: "Customer service essentials for hospitality roles.",
    provider: "Nepal Hospitality Academy",
    url: "https://example.com/nepal-hospitality",
    duration_hours: 6,
    difficulty_level: "Beginner",
    language: "English",
    price: 0,
    is_free: true,
    skill_names: ["Customer Service", "Communication"],
    tags: ["hospitality", "nepal"],
  },
];
