module.exports = [
  {
    name: "Content",
    category: "Other",
    description: "Write and structure content for digital platforms.",
    difficulty_level: "Beginner",
    learning_time_hours: 20,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Ads",
    category: "Other",
    description: "Plan and run paid digital advertising campaigns.",
    difficulty_level: "Beginner",
    learning_time_hours: 25,
    job_market_demand: "High",
    trending: true,
  },
  {
    name: "Analytics",
    category: "Data Science",
    description: "Measure and interpret data to drive decisions.",
    difficulty_level: "Beginner",
    learning_time_hours: 30,
    job_market_demand: "High",
    trending: true,
  },
  {
    name: "SEO",
    category: "Other",
    description: "Improve website visibility on search engines.",
    difficulty_level: "Beginner",
    learning_time_hours: 20,
    job_market_demand: "Medium",
    trending: true,
  },
  {
    name: "JavaScript",
    category: "Web Development",
    description: "Build interactive web applications with JavaScript.",
    difficulty_level: "Beginner",
    learning_time_hours: 40,
    job_market_demand: "High",
    trending: true,
  },
  {
    name: "APIs",
    category: "Web Development",
    description: "Design and consume web APIs for applications.",
    difficulty_level: "Intermediate",
    learning_time_hours: 35,
    job_market_demand: "High",
    trending: true,
  },
  {
    name: "Databases",
    category: "Data Science",
    description: "Store and manage data using relational databases.",
    difficulty_level: "Beginner",
    learning_time_hours: 35,
    job_market_demand: "High",
    trending: true,
  },
  {
    name: "Excel",
    category: "Data Science",
    description: "Analyze data and build reports with Excel.",
    difficulty_level: "Beginner",
    learning_time_hours: 20,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "SQL",
    category: "Data Science",
    description: "Query and analyze data using SQL.",
    difficulty_level: "Beginner",
    learning_time_hours: 30,
    job_market_demand: "High",
    trending: true,
  },
  {
    name: "Visualization",
    category: "Data Science",
    description: "Communicate insights with charts and dashboards.",
    difficulty_level: "Beginner",
    learning_time_hours: 25,
    job_market_demand: "Medium",
    trending: true,
  },
  {
    name: "AutoCAD",
    category: "Other",
    description: "Create technical drawings and plans.",
    difficulty_level: "Intermediate",
    learning_time_hours: 45,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Project Planning",
    category: "Other",
    description: "Plan, schedule, and track project work.",
    difficulty_level: "Intermediate",
    learning_time_hours: 30,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Surveying",
    category: "Other",
    description: "Collect land measurements and site data.",
    difficulty_level: "Intermediate",
    learning_time_hours: 30,
    job_market_demand: "Low",
    trending: false,
  },
  {
    name: "Patient Care",
    category: "Other",
    description: "Support patients with daily care routines.",
    difficulty_level: "Beginner",
    learning_time_hours: 30,
    job_market_demand: "High",
    trending: false,
  },
  {
    name: "Clinical Skills",
    category: "Other",
    description: "Perform clinical procedures safely.",
    difficulty_level: "Intermediate",
    learning_time_hours: 45,
    job_market_demand: "High",
    trending: false,
  },
  {
    name: "Communication",
    category: "Other",
    description: "Communicate clearly with teams and stakeholders.",
    difficulty_level: "Beginner",
    learning_time_hours: 15,
    job_market_demand: "High",
    trending: true,
  },
  {
    name: "Accounting",
    category: "Other",
    description: "Record and reconcile financial transactions.",
    difficulty_level: "Beginner",
    learning_time_hours: 35,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Tax",
    category: "Other",
    description: "Prepare and review tax filings.",
    difficulty_level: "Intermediate",
    learning_time_hours: 30,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Design",
    category: "Other",
    description: "Create visual layouts and assets.",
    difficulty_level: "Beginner",
    learning_time_hours: 30,
    job_market_demand: "Medium",
    trending: true,
  },
  {
    name: "Branding",
    category: "Other",
    description: "Build brand identity and guidelines.",
    difficulty_level: "Beginner",
    learning_time_hours: 25,
    job_market_demand: "Medium",
    trending: true,
  },
  {
    name: "UI",
    category: "Web Development",
    description: "Design intuitive user interfaces for web apps.",
    difficulty_level: "Beginner",
    learning_time_hours: 30,
    job_market_demand: "Medium",
    trending: true,
  },
  {
    name: "Operations",
    category: "Other",
    description: "Manage day-to-day business operations.",
    difficulty_level: "Intermediate",
    learning_time_hours: 35,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Customer Service",
    category: "Other",
    description: "Deliver quality service and support to customers.",
    difficulty_level: "Beginner",
    learning_time_hours: 20,
    job_market_demand: "High",
    trending: false,
  },
  {
    name: "Leadership",
    category: "Other",
    description: "Lead teams and drive outcomes.",
    difficulty_level: "Intermediate",
    learning_time_hours: 35,
    job_market_demand: "Medium",
    trending: true,
  },
  {
    name: "Soil",
    category: "Other",
    description: "Understand soil health and analysis.",
    difficulty_level: "Beginner",
    learning_time_hours: 20,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Crop Planning",
    category: "Other",
    description: "Plan crop cycles and farm outputs.",
    difficulty_level: "Beginner",
    learning_time_hours: 25,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Field Work",
    category: "Other",
    description: "Perform hands-on field operations.",
    difficulty_level: "Beginner",
    learning_time_hours: 20,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Finance",
    category: "Other",
    description: "Understand banking and financial operations.",
    difficulty_level: "Beginner",
    learning_time_hours: 30,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Teaching",
    category: "Other",
    description: "Deliver lessons and facilitate learning.",
    difficulty_level: "Beginner",
    learning_time_hours: 30,
    job_market_demand: "Low",
    trending: false,
  },
  {
    name: "Planning",
    category: "Other",
    description: "Organize coursework and lesson plans.",
    difficulty_level: "Beginner",
    learning_time_hours: 20,
    job_market_demand: "Low",
    trending: false,
  },
  {
    name: "Networking",
    category: "DevOps",
    description: "Configure and maintain network connectivity.",
    difficulty_level: "Intermediate",
    learning_time_hours: 40,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Troubleshooting",
    category: "DevOps",
    description: "Diagnose and resolve technical issues.",
    difficulty_level: "Intermediate",
    learning_time_hours: 35,
    job_market_demand: "Medium",
    trending: false,
  },
  {
    name: "Windows",
    category: "DevOps",
    description: "Administer Windows operating systems.",
    difficulty_level: "Beginner",
    learning_time_hours: 25,
    job_market_demand: "Medium",
    trending: false,
  },
];
